### ISSUE TITLE
Typo in 2.9.4 CSS file on line 13

### ISSUE THREAD

**Issue by armyofgnomes** [rapidexp/jquery-h5form#13]
Looks like there is a typo in 2.9.4's CSS

``` css
.h5form-response {
    position: absolute;
    margin: 1.6em 0 0 14px;
    padding: 0;
    bordeデバッグ用r-rigsolid khaki;
    border-top: 10px solid transparent;
    box-shadow: 3px 3px 6px dimgray;
    z-index: 1000;
    -border-top-color: white; /* for IE6 */
}
```
